name: 'fastmac_helloworld'
description: 'setup fastmac session'

inputs:
  ssh_key:
    description: 'private key'
    required: true
  key_file:
    description: 'ssh key file name'
    default: 'id_rsa'
    required: false

runs:
  using: "composite"
  steps:
    - name: keys
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/${{ inputs.key_file }}
        chmod 400 ~/.ssh/${{ inputs.key_file }}
        chmod 700 ~/.ssh
        cat << EOF > ~/.ssh/config
        Host *
            ServerAliveInterval 60
            StrictHostKeyChecking no
        Host github.com
            User git
            Port 22
            Hostname github.com
            TCPKeepAlive yes
            IdentitiesOnly yes
        EOF
    - name: source script-mac.sh
      shell: bash
      run: |
        source script-mac.sh


    - name: hostname
      shell: bash
      run: |
        hostname

runs:
  using: 'node12'
  main: 'node -v'