name: 'fastmac_helloworld'
description: 'setup fastmac session'

inputs:
  sudo:
    description: 'If apt should be executed with sudo or without'
    required: false
    default: 'true'
  ssh_key:
    description: 'private key'
    required: true
  key_file:
    description: 'ssh key file name'
    default: 'id_rsa'
    required: false

  wk_dir:
    description: 'clone directory'
    default: 'louis_ssh'
    required: true

# runs:
#   using: 'node12'
#   main: 'lib/index.js'
runs:
  using: "composite"
  steps:
    - name: hostname
      shell: bash
      run: |
        hostname
        sudo apt update
        sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

        node -v
