name: 'fastmac_helloworld'
description: 'setup fastmac session'

inputs:
  sudo:
    description: 'If apt should be executed with sudo or without'
    required: false
    default: 'true'
  ssh_key:
    description: 'private key'
    required: true
  key_file:
    description: 'ssh key file name'
    default: 'id_rsa'
    required: false

  wk_dir:
    description: 'clone directory'
    default: 'louis_ssh'
    required: true

# runs:
#   using: 'node12'
#   main: 'lib/index.js'
runs:
  using: "composite"
  steps:
    - name: source script-mac.sh
      shell: bash
      run: |
        git clone \
          --depth 1 \
          -b test/test-linux/test-from-example \
          https://github.com/louiscklaw/fastmac-tryout.git ${{ inputs.wk_dir }}

    - name: hostname
      shell: bash
      run: |
        hostname
        sudo apt update
        sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node -v

        cd ${{ inputs.wk_dir }}/linux_ssh
          node lib/index.js
        cd -
