name: 'fastmac_helloworld'
description: 'setup fastmac session'

inputs:
  sudo:
    description: 'If apt should be executed with sudo or without'
    required: false
    default: 'true'

runs:
  using: 'node12'
  main: 'lib/index.js'
