name: 'fastmac_helloworld'
description: 'setup fastmac session'

inputs:
  ssh_key:
    required: true

  key_file:
    required: true

runs:
  using: "composite"
  steps:
    - run: hostname
      shell: bash
