name: 'fastmac_helloworld'
description: 'setup fastmac session'

inputs:
  ssh_key:
    description: 'private key'
    required: true
  key_file:
    description: 'ssh key file name'
    default: 'id_rsa'
    required: false

runs:
  using: "composite"
  steps:
    - run: hostname
      shell: bash
