name: mac
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - run: hostname
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-mac.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2