on:
  push:
    branches:
      - test/test-linux/**
jobs:
  fastmac_helloworld_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-linux.sh
    - uses: fastmac-tryout/linux_ssh@test/test-linux/test-from-example
